---
title: "Writing Functions"
author: "Yue Liu"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document

---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(readxl)
library(patchwork)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

# z score
(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute z-scores

```{r}
# naming the input x
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x_vec)
```

Try my function on some othher things 

```{r error=TRUE}
z_scores(3) #NA
z_scores("my name is jeff") #Error
z_scores(mtcars) #Error
z_scores(c(TRUE, TRUE, FALSE, TRUE)) # 0.5  0.5 -1.5  0.5
```

update the function

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3){
    stop("Input must have at least three numbers ")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}
```

```{r error=TRUE}
z_scores(3) # Error in z_scores(3) : Input must have at least three numbers 
z_scores("my name is jeff") # Error in z_scores("my name is jeff") : Input must be numeric
```


## Multiple outputs

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3){
    stop("Input must have at least three numbers ")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean =  mean_x,
    sd = sd_x
  )

}
```

check if the function works

```{r}
x_vec = rnorm(100) # mean = 0, sd = 1
mean_and_sd(x_vec)
```

## Multiple inputs 

```{r}
sim_data = 
  tibble(
    x = rnorm(100, mean = 4, sd = 3) # x columns
  )

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```

translate into a function

```{r}
sim_mean_sd = function(samp_size, mu = 3, sigma = 4){
  
  sim_data = 
    tibble(
      x = rnorm(n = samp_size, mean = mu, sd = sigma) 
    )

  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}

sim_mean_sd(100, 6, 3) #positional matching
# the default mu and sigma will be overriden
sim_mean_sd(mu = 6, samp_size = 100, sigma = 3) #name matching

sim_mean_sd(samp_size = 100)
```

## Let's review Napoleon Dynamite

```{r}
nap_dyn_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

napoleon_html  = read_html(nap_dyn_url)

review_titles = 
  napoleon_html %>% 
  html_nodes(".a-text-bold span") %>% 
  html_text()

review_stars = 
  napoleon_html %>% 
  html_nodes("#cm_cr-review_list .review-rating") %>% 
  html_text() %>% 
  str_extract("^\\d") %>% 
  as.numeric()
  
review_text = 
  napoleon_html %>% 
  html_nodes(".review-text-content span") %>% 
  html_text()


review = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

What about the next page of reviews...

Let's turn that code into a function

```{r}
read_page_reviews = function(url){
  html  = read_html(url)

  review_titles = 
    html %>% 
    html_nodes(".a-text-bold span") %>% 
    html_text()

  review_stars = 
    html %>% 
    html_nodes("#cm_cr-review_list .review-rating") %>% 
    html_text() %>% 
    str_extract("^\\d") %>% 
    as.numeric()
    
  review_text = 
    html %>% 
    html_nodes(".review-text-content span") %>% 
    html_text()
  
  
  reviews = 
    tibble(
      title = review_titles,
      stars = review_stars,
      text = review_text
  )
  
  reviews
}
```

Let's try the function. 

```{r}
dynamite_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=2"

read_page_reviews(dynamite_url)
```

```{r}
dynamite_url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

dynamite_urls = str_c(dynamite_url_base, 1:5)

dynamite_urls[1] #the first page

all_reviews = 
  bind_rows(
    read_page_reviews(dynamite_urls[1]),
    read_page_reviews(dynamite_urls[2]),
    read_page_reviews(dynamite_urls[3]),
    read_page_reviews(dynamite_urls[4]),
    read_page_reviews(dynamite_urls[5])
  )
```

